2017/04/02 03:54:45 [error] [php] mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() (C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php:67)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#2 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#3 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#6 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/index.php?r=site/contact
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (67)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/02 04:11:14 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "say". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('say')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('say')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/say')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/index.php?r=site%2Fsay&message=Hello+World
---
2017/04/03 00:45:01 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index.maricoelquelolea". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('index.maricoelq...')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index.maricoelq...')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.mari...')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/index.maricoelquelolea
HTTP_REFERER=http://localhost/Prueba_Yii/site/login.maricoelquelolea
---
2017/04/03 00:52:57 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "Prueba_Yii/test/index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('Prueba_Yii/test...')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/Prueba_Yii/test/index
---
2017/04/03 01:05:59 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "gii". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('gii')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('gii')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/gii')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/gii
---
2017/04/03 01:15:43 [error] [exception.CHttpException.403] CHttpException: You are not authorized to perform this action. in C:\xampp\htdocs\Framework Yii\framework\web\auth\CAccessControlFilter.php:182
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\auth\CAccessControlFilter.php(145): CAccessControlFilter->accessDenied(Object(CWebUser), 'You are not aut...')
#1 C:\xampp\htdocs\Framework Yii\framework\web\filters\CFilter.php(38): CAccessControlFilter->preFilter(Object(CFilterChain))
#2 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(1145): CFilter->filter(Object(CFilterChain))
#3 C:\xampp\htdocs\Framework Yii\framework\web\filters\CInlineFilter.php(58): CController->filterAccessControl(Object(CFilterChain))
#4 C:\xampp\htdocs\Framework Yii\framework\web\filters\CFilterChain.php(130): CInlineFilter->filter(Object(CFilterChain))
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(291): CFilterChain->run()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('admin')
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('users/admin')
#9 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#11 {main}
REQUEST_URI=/Prueba_Yii/users/admin
HTTP_REFERER=http://localhost/Prueba_Yii/users
---
2017/04/03 04:06:06 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index.html". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index.html')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index.html
HTTP_REFERER=http://localhost/Prueba_Yii/
---
2017/04/03 04:07:06 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index.html". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index.html')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index.html
HTTP_REFERER=http://localhost/Prueba_Yii/
---
2017/04/03 04:13:07 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index.html". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index.html')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index.html
HTTP_REFERER=http://localhost/Prueba_Yii/
---
2017/04/03 04:14:46 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index.html". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index.html')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index.html
HTTP_REFERER=http://localhost/Prueba_Yii/
---
2017/04/03 04:28:12 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "panels-wells.html". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('panels-wells.ht...')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/panels-wells.html
HTTP_REFERER=http://localhost/Prueba_Yii/
---
2017/04/03 04:30:43 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "notifications_panel.php". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('notifications_p...')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/notifications_panel.php
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/03 04:42:41 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "notifications_panel.php". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('notifications_p...')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/notifications_panel.php
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/03 04:43:34 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "notifications_panel.php". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('notifications_p...')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/notifications_panel.php
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/03 04:45:17 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "notificationspanel.php". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('notificationspa...')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/notificationspanel.php
---
2017/04/03 04:45:20 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "notificationspanel". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('notificationspa...')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/notificationspanel
---
2017/04/03 04:45:34 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "notifications_panel.php". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('notifications_p...')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/notifications_panel.php
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/03 04:51:47 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
HTTP_REFERER=http://localhost/Prueba_Yii/
---
2017/04/03 04:59:31 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "notifications_panel.php". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('notifications_p...')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/notifications_panel.php
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/03 05:01:35 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "notificationspanel.php". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('notificationspa...')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/notificationspanel.php
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/03 05:06:10 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
---
2017/04/03 05:06:14 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
---
2017/04/03 05:06:32 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "notificationspanel.php". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('notificationspa...')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('notificationspa...')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/notificati...')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/notificationspanel.php
HTTP_REFERER=http://localhost/Prueba_Yii/site/index
---
2017/04/03 05:06:36 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "notificationspanel". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('notificationspa...')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('notificationspa...')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/notificati...')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/notificationspanel
---
2017/04/03 05:08:29 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index.php". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/index.php
HTTP_REFERER=http://localhost/Prueba_Yii/site/index
---
2017/04/03 05:08:38 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/03 05:09:10 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/03 05:09:12 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/03 05:09:14 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "inde". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('inde')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/inde
---
2017/04/03 05:23:50 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "login". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/login
---
2017/04/03 05:23:56 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "login.php". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('login.php')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/login.php
---
2017/04/03 05:24:03 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "login.php". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('login.php')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('login.php')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.php')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/login.php
---
2017/04/03 05:32:53 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "login.php". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('login.php')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/login.php
---
2017/04/03 05:33:01 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "login". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/login
---
2017/04/04 02:15:50 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "login.php". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('login.php')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/login.php
---
2017/04/04 02:15:55 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "login". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('login')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/login
---
2017/04/04 02:16:00 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
---
2017/04/04 02:16:23 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "about". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('about')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('about')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/about')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/about
---
2017/04/04 02:16:33 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "pages". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('pages')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('pages')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/pages/abou...')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/pages/about
---
2017/04/04 02:51:10 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index.php". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/index.php
HTTP_REFERER=http://localhost/Prueba_Yii/site/contact
---
2017/04/04 02:51:17 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index.php". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/index.php
HTTP_REFERER=http://localhost/Prueba_Yii/site/index
---
2017/04/04 02:51:32 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index.php". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/index.php
HTTP_REFERER=http://localhost/Prueba_Yii/site/index
---
2017/04/04 02:52:00 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
---
2017/04/04 02:52:06 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/04 02:52:28 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "site". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/site/index')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/site/index
HTTP_REFERER=http://localhost/Prueba_Yii/site/index
---
2017/04/04 03:17:29 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "site". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/site/index')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/site/index
HTTP_REFERER=http://localhost/Prueba_Yii/site/login
---
2017/04/04 03:17:33 [error] [exception.Error] Error: Access to undeclared static property: Yii::$app in C:\xampp\htdocs\Prueba_Yii\protected\views\layouts\main.php:60
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#2 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(32): CController->render('index')
#4 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index')
#9 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#10 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Prueba_Yii/site/index
---
2017/04/04 03:17:42 [error] [exception.Error] Error: Access to undeclared static property: Yii::$app in C:\xampp\htdocs\Prueba_Yii\protected\views\layouts\main.php:60
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#2 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(32): CController->render('index')
#4 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#10 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Prueba_Yii/index.php
---
2017/04/04 03:17:46 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
---
2017/04/04 03:17:53 [error] [exception.Error] Error: Access to undeclared static property: Yii::$app in C:\xampp\htdocs\Prueba_Yii\protected\views\layouts\main.php:60
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CBaseController.php(126): require()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CBaseController.php(95): CBaseController->renderInternal('C:\\xampp\\htdocs...', Array, true)
#2 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(784): CBaseController->renderFile('C:\\xampp\\htdocs...', Array, true)
#3 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(32): CController->render('index')
#4 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#7 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#9 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site')
#10 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#11 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#12 {main}
REQUEST_URI=/Prueba_Yii/site/
---
2017/04/04 03:18:12 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "site". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/site/index')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/site/index
HTTP_REFERER=http://localhost/Prueba_Yii/site/
---
2017/04/04 03:31:39 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "site". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('site')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('site')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/site/index')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/site/index
HTTP_REFERER=http://localhost/Prueba_Yii/site/login
---
2017/04/04 03:45:20 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
HTTP_REFERER=http://localhost/Prueba_Yii/index.php
---
2017/04/04 04:26:44 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php:32)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/
in C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php (32)
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/04 04:26:51 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php:32)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/site/
in C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php (32)
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/04 04:27:11 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\controllers\TestController.php:8)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): TestController->runAction()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): TestController->runActionWithFilters()
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): TestController->run()
#3 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/test
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\TestController.php (8)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/04 04:27:22 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "login.html". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('login.html')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/login.html
HTTP_REFERER=http://localhost/Prueba_Yii/users
---
2017/04/04 04:27:32 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php:32)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/index.php
in C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php (32)
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/04 04:27:39 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index.php". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/index.php
---
2017/04/04 04:27:42 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php:32)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/site/index
in C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php (32)
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/04 04:31:07 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php:32)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(32): SiteController->render()
#3 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/
in C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php (32)
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (32)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/04 04:32:36 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "login.html". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('login.html')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('login.html')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login.html')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/login.html
HTTP_REFERER=http://localhost/Prueba_Yii/site/index
---
2017/04/04 04:43:17 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index.php". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/index.php
HTTP_REFERER=http://localhost/Prueba_Yii/site/index
---
2017/04/04 04:43:20 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index.php". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/index.php
---
2017/04/04 04:43:30 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index.php". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('index.php')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index.php')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index.php')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/index.php
HTTP_REFERER=http://localhost/Prueba_Yii/site/index
---
2017/04/05 01:12:17 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php:32)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(34): SiteController->render()
#3 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/
in C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php (32)
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (34)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/05 01:12:37 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php:32)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(34): SiteController->render()
#3 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/
in C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php (32)
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (34)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/05 01:13:55 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php:32)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(34): SiteController->render()
#3 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/site/index
in C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php (32)
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (34)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/05 01:14:24 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php:33)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(782): SiteController->renderPartial()
#2 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(34): SiteController->render()
#3 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#8 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#10 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/site/index
in C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php (33)
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (34)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/05 01:20:11 [error] [php] Undefined variable: model (C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php:68)
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(869): SiteController->renderFile()
#1 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(34): SiteController->renderPartial()
#2 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#3 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#7 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#8 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#9 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/site/
in C:\xampp\htdocs\Prueba_Yii\protected\views\site\login.php (68)
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (34)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/05 01:22:36 [error] [php] include(YourModel.php): failed to open stream: No such file or directory (C:\xampp\htdocs\Framework Yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(30): spl_autoload_call()
#1 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/site/
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (30)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/05 01:22:59 [error] [php] include(YourModel.php): failed to open stream: No such file or directory (C:\xampp\htdocs\Framework Yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(30): spl_autoload_call()
#1 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (30)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/05 01:23:12 [error] [php] include(YourModel.php): failed to open stream: No such file or directory (C:\xampp\htdocs\Framework Yii\framework\YiiBase.php:432)
Stack trace:
#0 C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php(30): spl_autoload_call()
#1 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#2 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\Prueba_Yii\index.php(13): CWebApplication->run()
REQUEST_URI=/Prueba_Yii/site/index
in C:\xampp\htdocs\Prueba_Yii\protected\controllers\SiteController.php (30)
in C:\xampp\htdocs\Prueba_Yii\index.php (13)
2017/04/05 01:32:43 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "index". in C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('index')
#1 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Prueba_Yii/index
---
2017/04/05 01:48:10 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('index')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Prueba_Yii\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Prueba_Yii/site/index
HTTP_REFERER=http://localhost/Prueba_Yii/site/index
---
2017/04/05 02:27:04 [error] [php] Cannot modify header information - headers already sent by (output started at C:\xampp\htdocs\Framework Yii\framework\web\CController.php:875) (C:\xampp\htdocs\Framework Yii\framework\web\CHttpRequest.php:889)
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\protected\controllers\SiteController.php(99): SiteController->redirect()
#1 C:\xampp\htdocs\Framework Yii\framework\web\actions\CInlineAction.php(49): SiteController->actionLogin()
#2 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#3 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#4 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#5 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#6 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#7 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#8 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CWebApplication->run()
REQUEST_URI=/Yii_Salvatore/site/login
in C:\xampp\htdocs\Yii_Salvatore\protected\controllers\SiteController.php (99)
in C:\xampp\htdocs\Yii_Salvatore\index.php (13)
2017/04/05 02:27:49 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/
---
2017/04/05 02:29:52 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Framework Yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site')
#3 C:\xampp\htdocs\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/site/
---
2017/04/05 02:34:24 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/
HTTP_REFERER=http://localhost/Yii_Salvatore/site/login
---
2017/04/05 02:36:44 [error] [exception.CHttpException.404] CHttpException: Unable to resolve the request "panel". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('panel')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#2 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/Yii_Salvatore/panel
---
2017/04/05 02:37:17 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/
---
2017/04/05 02:37:48 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/
HTTP_REFERER=http://localhost/Yii_Salvatore/site/login
---
2017/04/05 02:38:12 [error] [php] Undefined variable: model (C:\xampp\htdocs\Yii_Salvatore\protected\controllers\SiteController.php:110)
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(286): SiteController->runAction()
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): SiteController->run()
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#5 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CWebApplication->run()
REQUEST_URI=/Yii_Salvatore/site/logout
in C:\xampp\htdocs\Yii_Salvatore\protected\controllers\SiteController.php (110)
in C:\xampp\htdocs\Yii_Salvatore\index.php (13)
2017/04/05 02:42:51 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "localhost". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(270): CController->missingAction('localhost')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): CController->run('localhost')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/localhost/...')
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/site/localhost/Yii_Salvatore/site/panel
---
2017/04/05 03:07:53 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site')
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/site/
---
2017/04/05 03:11:22 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site')
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/site/
---
2017/04/05 03:13:55 [error] [exception.ParseError] ParseError: syntax error, unexpected ''panel'' (T_CONSTANT_ENCAPSED_STRING), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in C:\xampp\htdocs\Yii_Salvatore\protected\controllers\SiteController.php:96
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(276): CWebApplication->createController('login/')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/login')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#3 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#4 {main}
REQUEST_URI=/Yii_Salvatore/site/login
---
2017/04/05 03:14:24 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/
---
2017/04/05 03:14:34 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(270): CController->missingAction('index')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/site/index
---
2017/04/05 03:17:30 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(270): CController->missingAction('')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): CController->run('')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/
---
2017/04/05 03:28:01 [error] [exception.CHttpException.404] CHttpException: The system is unable to find the requested action "index". in C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php:483
Stack trace:
#0 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CController.php(270): CController->missingAction('index')
#1 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(282): CController->run('index')
#2 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/index')
#3 C:\xampp\htdocs\Yii_Salvatore\Framework Yii\framework\base\CApplication.php(185): CWebApplication->processRequest()
#4 C:\xampp\htdocs\Yii_Salvatore\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/Yii_Salvatore/site/index
HTTP_REFERER=http://localhost/Yii_Salvatore/site/login
---
